version: "3.8"

services:

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-1

  db:
    image: mysql:8.3.0
    container_name: mysql_db_Real-Time_Delivery_Tracking_System
    command: mysqld --default_authentication_plugin=caching_sha2_password

    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: ${DB_PORT}


    ports:
      - "${DB_EXPOSE_PORT}:${DB_PORT}"

    expose:
      - ${DB_PORT}

    networks:
      - Real-Time_Delivery_Tracking_System_network

    volumes:
      - mysql_data:/var/lib/mysql

  real-time_delivery_tracking_system:
    build: .
    image: guilhermebauer/real-timedeliverytrackingsystem:latest
    container_name: Real-Time_Delivery_Tracking_System
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SECRET_KEY: ${SECRET_KEY}
      TEST_MAIL: ${TEST_MAIL}
      NROK_URL: ${NROK_URL}
      MERCADO_PAGO_PUBLIC_KEY: ${MERCADO_PAGO_PUBLIC_KEY}
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      SPRING_MAIL_USERNAME: ${JAVA_MAIL_EMAIL}
      SPRING_MAIL_PASSWORD: ${JAVA_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: smtp.gmail.com
      SPRING_MAIL_TEST-CONNECTION: "true"

    ports:
      - "${EXPOSE_PORT}:${CONTAINER_PORT}"
    depends_on:
      - db
    networks:
      - Real-Time_Delivery_Tracking_System_network

networks:
  Real-Time_Delivery_Tracking_System_network:
    driver: bridge

volumes:
  mysql_data:
