FROM openjdk:21-jdk-slim

ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_PORT
ARG DB_EXPOSE_PORT
ARG EXPOSE_PORT
ARG CONTAINER_PORT
ARG SECRET_KEY
ARG JAVA_MAIL_EMAIL
ARG JAVA_MAIL_PASSWORD
ARG TEST_MAIL
ARG NROK_URL
ARG MERCADO_PAGO_PUBLIC_KEY
ARG MERCADO_PAGO_ACCESS_TOKEN
ARG MERCADO_PAGO_WEBHOOK_SECRET
ARG KAFKA_BOOTSTRAP_SERVERS

ENV DB_NAME=${DB_NAME} \
    DB_USERNAME=${DB_USERNAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    DB_PORT=${DB_PORT} \
    EXPOSE_PORT=${EXPOSE_PORT} \
    DB_EXPOSE_PORT=${DB_EXPOSE_PORT} \
    CONTAINER_PORT=${CONTAINER_PORT} \
    SECRET_KEY=${SECRET_KEY} \
    JAVA_MAIL_EMAIL=${JAVA_MAIL_EMAIL} \
    JAVA_MAIL_PASSWORD=${JAVA_MAIL_PASSWORD} \
    TEST_MAIL=${TEST_MAIL} \
    NROK_URL=${NROK_URL} \
    MERCADO_PAGO_PUBLIC_KEY=${MERCADO_PAGO_PUBLIC_KEY} \
    MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN} \
    MERCADO_PAGO_WEBHOOK_SECRET=${MERCADO_PAGO_WEBHOOK_SECRET} \
    KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

WORKDIR /app

COPY target/*.jar /app/Real-TimeDeliveryTrackingSystem.jar

EXPOSE ${EXPOSE_PORT}

ENTRYPOINT ["java", "-jar", "Real-TimeDeliveryTrackingSystem.jar"]
